#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 1
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 150
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 200
    rateControl:
    - type: fixed-rate
      opts:
        tps: 40
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 250
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 300
    rateControl:
    - type: fixed-rate
      opts:
        tps: 60
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 350
    rateControl:
    - type: fixed-rate
      opts:
        tps: 70
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 400
    rateControl:
    - type: fixed-rate
      opts:
        tps: 80
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 450
    rateControl:
    - type: fixed-rate
      opts:
        tps: 90
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 550
    rateControl:
    - type: fixed-rate
      opts:
        tps: 110
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 600
    rateControl:
    - type: fixed-rate
      opts:
        tps: 120
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 650
    rateControl:
    - type: fixed-rate
      opts:
        tps: 130
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 700
    rateControl:
    - type: fixed-rate
      opts:
        tps: 140
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 750
    rateControl:
    - type: fixed-rate
      opts:
        tps: 150
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 800
    rateControl:
    - type: fixed-rate
      opts:
        tps: 160
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 850
    rateControl:
    - type: fixed-rate
      opts:
        tps: 170
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 900
    rateControl:
    - type: fixed-rate
      opts:
        tps: 180
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 950
    rateControl:
    - type: fixed-rate
      opts:
        tps: 190
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 200
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
